# 生成文章的目录位置
# permalink: /:year-:month-:day/:title/
permalink: /:categories/:year-:month-:day-:title.html
# Site settings
title: 逆水行舟
email: rgkjhshi@gmail.com
description: Michael King's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  rgkjhshi
# url: "http://loveshisong.cn"
url: "http://127.0.0.1:4000"

# Build settings
# 代码高亮
highlighter: pygments # 高亮显示 取值有 'rouge', 'pygments'
# markdown 的解释器, 默认是 kramdown
markdown: redcarpet
# 关闭安全模式，以便 Jekyll 解析时会运行插件
safe: false
# 指定摘要分割符号
# excerpt_separator: "\n\n\n"
# 指定分页时一页大小
# paginate: 5
# paginate_path: ":num"

# 多说评论系统
comments :
    provider : duoshuo
    duoshuo : Michael
    short_name : Michael

# 官方说明 https://github.com/vmg/redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"   # 不解析单词中的下划线
   ,"fenced_code_blocks" # 三个 ~ 或 ` 包围的文本会被解析成代码块
   # ,"autolink"           # 自动链接
   ,"tables"             # |---|:---|---:|:---:| 上面一行是表头
   ,"strikethrough"      # 两个 ~ 包围的会解析成删除线
   ,"superscript"        # 上标 文本^上标一^^上标二
   ,"with_toc_data"      # 给生成的 Header 标签增加锚点
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
   ,"html_toc"
#   ,"space_after_headers" #后面必须加空格，否则不会被解析为标题
  ]
